// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rawrpcpb.proto

package kvrawpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KvPair struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvPair) Reset()         { *m = KvPair{} }
func (m *KvPair) String() string { return proto.CompactTextString(m) }
func (*KvPair) ProtoMessage()    {}
func (*KvPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{0}
}

func (m *KvPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvPair.Unmarshal(m, b)
}
func (m *KvPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvPair.Marshal(b, m, deterministic)
}
func (m *KvPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvPair.Merge(m, src)
}
func (m *KvPair) XXX_Size() int {
	return xxx_messageInfo_KvPair.Size(m)
}
func (m *KvPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KvPair.DiscardUnknown(m)
}

var xxx_messageInfo_KvPair proto.InternalMessageInfo

func (m *KvPair) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KvPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RawScanRequest struct {
	StartKey []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit    uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	KeyOnly  bool   `protobuf:"varint,4,opt,name=key_only,json=keyOnly,proto3" json:"key_only,omitempty"`
	Cf       string `protobuf:"bytes,5,opt,name=cf,proto3" json:"cf,omitempty"`
	Reverse  bool   `protobuf:"varint,6,opt,name=reverse,proto3" json:"reverse,omitempty"`
	// For compatibility, when scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
	// and when scanning backward, it scans [end_key, start_key) in descending order, where end_key < start_key.
	EndKey               []byte   `protobuf:"bytes,7,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawScanRequest) Reset()         { *m = RawScanRequest{} }
func (m *RawScanRequest) String() string { return proto.CompactTextString(m) }
func (*RawScanRequest) ProtoMessage()    {}
func (*RawScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{1}
}

func (m *RawScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawScanRequest.Unmarshal(m, b)
}
func (m *RawScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawScanRequest.Marshal(b, m, deterministic)
}
func (m *RawScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawScanRequest.Merge(m, src)
}
func (m *RawScanRequest) XXX_Size() int {
	return xxx_messageInfo_RawScanRequest.Size(m)
}
func (m *RawScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawScanRequest proto.InternalMessageInfo

func (m *RawScanRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RawScanRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RawScanRequest) GetKeyOnly() bool {
	if m != nil {
		return m.KeyOnly
	}
	return false
}

func (m *RawScanRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

func (m *RawScanRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *RawScanRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

type RawScanResponse struct {
	RegionError          *Error    `protobuf:"bytes,1,opt,name=region_error,json=regionError,proto3" json:"region_error,omitempty"`
	Kvs                  []*KvPair `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RawScanResponse) Reset()         { *m = RawScanResponse{} }
func (m *RawScanResponse) String() string { return proto.CompactTextString(m) }
func (*RawScanResponse) ProtoMessage()    {}
func (*RawScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{2}
}

func (m *RawScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawScanResponse.Unmarshal(m, b)
}
func (m *RawScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawScanResponse.Marshal(b, m, deterministic)
}
func (m *RawScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawScanResponse.Merge(m, src)
}
func (m *RawScanResponse) XXX_Size() int {
	return xxx_messageInfo_RawScanResponse.Size(m)
}
func (m *RawScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawScanResponse proto.InternalMessageInfo

func (m *RawScanResponse) GetRegionError() *Error {
	if m != nil {
		return m.RegionError
	}
	return nil
}

func (m *RawScanResponse) GetKvs() []*KvPair {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type RawGetRequest struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetRequest) Reset()         { *m = RawGetRequest{} }
func (m *RawGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawGetRequest) ProtoMessage()    {}
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{3}
}

func (m *RawGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetRequest.Unmarshal(m, b)
}
func (m *RawGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetRequest.Marshal(b, m, deterministic)
}
func (m *RawGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetRequest.Merge(m, src)
}
func (m *RawGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawGetRequest.Size(m)
}
func (m *RawGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetRequest proto.InternalMessageInfo

func (m *RawGetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawGetRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawGetResponse struct {
	RegionError          *Error   `protobuf:"bytes,1,opt,name=region_error,json=regionError,proto3" json:"region_error,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	NotFound             bool     `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetResponse) Reset()         { *m = RawGetResponse{} }
func (m *RawGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawGetResponse) ProtoMessage()    {}
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{4}
}

func (m *RawGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetResponse.Unmarshal(m, b)
}
func (m *RawGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetResponse.Marshal(b, m, deterministic)
}
func (m *RawGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetResponse.Merge(m, src)
}
func (m *RawGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawGetResponse.Size(m)
}
func (m *RawGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetResponse proto.InternalMessageInfo

func (m *RawGetResponse) GetRegionError() *Error {
	if m != nil {
		return m.RegionError
	}
	return nil
}

func (m *RawGetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RawGetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawGetResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type RawPutRequest struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Cf                   string   `protobuf:"bytes,4,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutRequest) Reset()         { *m = RawPutRequest{} }
func (m *RawPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawPutRequest) ProtoMessage()    {}
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{5}
}

func (m *RawPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutRequest.Unmarshal(m, b)
}
func (m *RawPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutRequest.Marshal(b, m, deterministic)
}
func (m *RawPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutRequest.Merge(m, src)
}
func (m *RawPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawPutRequest.Size(m)
}
func (m *RawPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutRequest proto.InternalMessageInfo

func (m *RawPutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawPutRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawPutResponse struct {
	RegionError          *Error   `protobuf:"bytes,1,opt,name=region_error,json=regionError,proto3" json:"region_error,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutResponse) Reset()         { *m = RawPutResponse{} }
func (m *RawPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawPutResponse) ProtoMessage()    {}
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{6}
}

func (m *RawPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutResponse.Unmarshal(m, b)
}
func (m *RawPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutResponse.Marshal(b, m, deterministic)
}
func (m *RawPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutResponse.Merge(m, src)
}
func (m *RawPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawPutResponse.Size(m)
}
func (m *RawPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutResponse proto.InternalMessageInfo

func (m *RawPutResponse) GetRegionError() *Error {
	if m != nil {
		return m.RegionError
	}
	return nil
}

func (m *RawPutResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawDeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRequest) Reset()         { *m = RawDeleteRequest{} }
func (m *RawDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRequest) ProtoMessage()    {}
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{7}
}

func (m *RawDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRequest.Unmarshal(m, b)
}
func (m *RawDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRequest.Merge(m, src)
}
func (m *RawDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRequest.Size(m)
}
func (m *RawDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRequest proto.InternalMessageInfo

func (m *RawDeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawDeleteRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawDeleteResponse struct {
	RegionError          *Error   `protobuf:"bytes,1,opt,name=region_error,json=regionError,proto3" json:"region_error,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteResponse) Reset()         { *m = RawDeleteResponse{} }
func (m *RawDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteResponse) ProtoMessage()    {}
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da60b38498eabb5, []int{8}
}

func (m *RawDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteResponse.Unmarshal(m, b)
}
func (m *RawDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteResponse.Merge(m, src)
}
func (m *RawDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteResponse.Size(m)
}
func (m *RawDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteResponse proto.InternalMessageInfo

func (m *RawDeleteResponse) GetRegionError() *Error {
	if m != nil {
		return m.RegionError
	}
	return nil
}

func (m *RawDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*KvPair)(nil), "kvrawpb.KvPair")
	proto.RegisterType((*RawScanRequest)(nil), "kvrawpb.RawScanRequest")
	proto.RegisterType((*RawScanResponse)(nil), "kvrawpb.RawScanResponse")
	proto.RegisterType((*RawGetRequest)(nil), "kvrawpb.RawGetRequest")
	proto.RegisterType((*RawGetResponse)(nil), "kvrawpb.RawGetResponse")
	proto.RegisterType((*RawPutRequest)(nil), "kvrawpb.RawPutRequest")
	proto.RegisterType((*RawPutResponse)(nil), "kvrawpb.RawPutResponse")
	proto.RegisterType((*RawDeleteRequest)(nil), "kvrawpb.RawDeleteRequest")
	proto.RegisterType((*RawDeleteResponse)(nil), "kvrawpb.RawDeleteResponse")
}

func init() {
	proto.RegisterFile("rawrpcpb.proto", fileDescriptor_9da60b38498eabb5)
}

var fileDescriptor_9da60b38498eabb5 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0xc4, 0x4e, 0x26, 0x4d, 0x5a, 0x56, 0x15, 0x75, 0xcd, 0xc5, 0xf8, 0xe4, 0x53,
	0x44, 0x03, 0x37, 0x24, 0x4e, 0x85, 0x1e, 0x72, 0x20, 0x5a, 0xb8, 0x20, 0x21, 0x45, 0x4e, 0x32,
	0xa9, 0x2c, 0x9b, 0x5d, 0xb3, 0x5e, 0xdb, 0xf2, 0x0f, 0x70, 0xe2, 0x27, 0xf8, 0x53, 0xe4, 0x5d,
	0xdb, 0x4d, 0x48, 0x84, 0x10, 0xea, 0x29, 0x99, 0xd9, 0x79, 0x6f, 0xe6, 0xbd, 0xd9, 0x35, 0x4c,
	0x45, 0x58, 0x8a, 0x74, 0x93, 0xae, 0x67, 0xa9, 0xe0, 0x92, 0x13, 0x3b, 0x2e, 0x44, 0x58, 0xa6,
	0x6b, 0x77, 0x82, 0x42, 0x70, 0xd1, 0xe6, 0xfd, 0x57, 0x60, 0x2d, 0x8a, 0x65, 0x18, 0x09, 0x72,
	0x09, 0xbd, 0x18, 0x2b, 0xc7, 0xf4, 0x8c, 0xe0, 0x9c, 0xd6, 0x7f, 0xc9, 0x15, 0x0c, 0x8a, 0x30,
	0xc9, 0xd1, 0xe9, 0xa9, 0x9c, 0x0e, 0xfc, 0x5f, 0x06, 0x4c, 0x69, 0x58, 0x7e, 0xda, 0x84, 0x8c,
	0xe2, 0xf7, 0x1c, 0x33, 0x49, 0x5e, 0xc0, 0x28, 0x93, 0xa1, 0x90, 0xab, 0x47, 0x82, 0xa1, 0x4a,
	0x2c, 0x34, 0x4b, 0x12, 0x7d, 0x8b, 0xa4, 0x62, 0x99, 0x50, 0x1d, 0x90, 0x1b, 0x18, 0xc6, 0x58,
	0xad, 0x38, 0x4b, 0x2a, 0xa7, 0xef, 0x19, 0xc1, 0x90, 0xda, 0x31, 0x56, 0x1f, 0x59, 0x52, 0x91,
	0x29, 0x98, 0x9b, 0x9d, 0x33, 0xf0, 0x8c, 0x60, 0x44, 0xcd, 0xcd, 0x8e, 0x38, 0x60, 0x0b, 0x2c,
	0x50, 0x64, 0xe8, 0x58, 0xba, 0xb2, 0x09, 0xc9, 0x35, 0xd8, 0xc8, 0xb6, 0xaa, 0xab, 0xad, 0xba,
	0x5a, 0xc8, 0xb6, 0x0b, 0xac, 0xfc, 0x07, 0xb8, 0xe8, 0x46, 0xcc, 0x52, 0xce, 0x32, 0x24, 0xb7,
	0x70, 0x2e, 0xf0, 0x21, 0xe2, 0x6c, 0xa5, 0x0c, 0x70, 0x0c, 0xcf, 0x08, 0xc6, 0xf3, 0xe9, 0xac,
	0xb5, 0xe3, 0x7d, 0xfd, 0x4b, 0xc7, 0xba, 0x46, 0x05, 0xe4, 0x25, 0xf4, 0xe2, 0x22, 0x73, 0x4c,
	0xaf, 0x17, 0x8c, 0xe7, 0x17, 0xb3, 0xc6, 0xc1, 0x99, 0xf6, 0x8b, 0xd6, 0x67, 0xfe, 0x2d, 0x4c,
	0x68, 0x58, 0xde, 0xa3, 0x6c, 0xad, 0x38, 0x76, 0x51, 0xcb, 0xe9, 0xb5, 0x72, 0xfc, 0x9f, 0xda,
	0x3f, 0x85, 0xf9, 0xff, 0xd9, 0xae, 0x60, 0xa0, 0x6b, 0x4d, 0x45, 0xac, 0x83, 0xd3, 0x1b, 0xab,
	0xd7, 0xc3, 0xb8, 0x5c, 0xed, 0x78, 0xce, 0xb6, 0x8d, 0xd9, 0x43, 0xc6, 0xe5, 0x87, 0x3a, 0xf6,
	0xef, 0x95, 0x82, 0x65, 0xfe, 0x17, 0x05, 0xa7, 0x59, 0xb5, 0xae, 0x7e, 0xa7, 0xeb, 0x8b, 0x92,
	0xa5, 0x88, 0x9e, 0x58, 0x96, 0xff, 0x06, 0x2e, 0x69, 0x58, 0xde, 0x61, 0x82, 0x12, 0xff, 0xdd,
	0xe8, 0xaf, 0xf0, 0x6c, 0x0f, 0xf5, 0xc4, 0x33, 0xcd, 0x7f, 0x98, 0xd0, 0xff, 0x1c, 0xc5, 0x05,
	0x79, 0x0b, 0x96, 0x5e, 0x27, 0x79, 0xde, 0x5d, 0x91, 0x83, 0x3b, 0xe1, 0x5e, 0x1f, 0xe5, 0xf5,
	0x30, 0xfe, 0x59, 0x03, 0x5e, 0xe6, 0x7f, 0x80, 0x1f, 0xd7, 0x71, 0x08, 0xde, 0x73, 0xd7, 0x3f,
	0x23, 0x77, 0x30, 0xea, 0x04, 0x92, 0x9b, 0xfd, 0xba, 0x03, 0xab, 0x5c, 0xf7, 0xd4, 0x51, 0xc7,
	0xf2, 0x0e, 0xec, 0xe6, 0xad, 0x90, 0x83, 0x5e, 0x7b, 0x0f, 0xdc, 0x75, 0x8e, 0x0f, 0x5a, 0xfc,
	0xda, 0x52, 0x1f, 0x92, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x74, 0x75, 0x3f, 0x2b, 0x72,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TikvClient is the client API for Tikv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TikvClient interface {
	// RawKV commands.
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
	RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error)
}

type tikvClient struct {
	cc grpc.ClientConnInterface
}

func NewTikvClient(cc grpc.ClientConnInterface) TikvClient {
	return &tikvClient{cc}
}

func (c *tikvClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, "/kvrawpb.Tikv/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, "/kvrawpb.Tikv/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/kvrawpb.Tikv/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tikvClient) RawScan(ctx context.Context, in *RawScanRequest, opts ...grpc.CallOption) (*RawScanResponse, error) {
	out := new(RawScanResponse)
	err := c.cc.Invoke(ctx, "/kvrawpb.Tikv/RawScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TikvServer is the server API for Tikv service.
type TikvServer interface {
	// RawKV commands.
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
	RawScan(context.Context, *RawScanRequest) (*RawScanResponse, error)
}

// UnimplementedTikvServer can be embedded to have forward compatible implementations.
type UnimplementedTikvServer struct {
}

func (*UnimplementedTikvServer) RawGet(ctx context.Context, req *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (*UnimplementedTikvServer) RawPut(ctx context.Context, req *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (*UnimplementedTikvServer) RawDelete(ctx context.Context, req *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}
func (*UnimplementedTikvServer) RawScan(ctx context.Context, req *RawScanRequest) (*RawScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawScan not implemented")
}

func RegisterTikvServer(s *grpc.Server, srv TikvServer) {
	s.RegisterService(&_Tikv_serviceDesc, srv)
}

func _Tikv_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvrawpb.Tikv/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tikv_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvrawpb.Tikv/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tikv_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvrawpb.Tikv/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tikv_RawScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TikvServer).RawScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvrawpb.Tikv/RawScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TikvServer).RawScan(ctx, req.(*RawScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tikv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvrawpb.Tikv",
	HandlerType: (*TikvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _Tikv_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _Tikv_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _Tikv_RawDelete_Handler,
		},
		{
			MethodName: "RawScan",
			Handler:    _Tikv_RawScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rawrpcpb.proto",
}
